// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PayrollService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318005538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BasicSalary")
                        .HasColumnType("float");

                    b.Property<double>("Bonus")
                        .HasColumnType("float");

                    b.Property<double>("Deductions")
                        .HasColumnType("float");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HousingAllowance")
                        .HasColumnType("float");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<double>("NetSalary")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TransportAllowance")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payrolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasicSalary = 12000.0,
                            Bonus = 500.0,
                            Deductions = 0.0,
                            EmployeeId = 1,
                            EmployeeName = "Ahmed Al-Rashid",
                            HousingAllowance = 2400.0,
                            Month = 3,
                            NetSalary = 15700.0,
                            Status = "Paid",
                            TransportAllowance = 800.0,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            BasicSalary = 15000.0,
                            Bonus = 1000.0,
                            Deductions = 0.0,
                            EmployeeId = 2,
                            EmployeeName = "Sara Al-Qahtani",
                            HousingAllowance = 3000.0,
                            Month = 3,
                            NetSalary = 19800.0,
                            Status = "Paid",
                            TransportAllowance = 800.0,
                            Year = 2026
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
